name: "JFrog Integration Example"
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: 2.52.9
        env:  
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Set CLI Config
        run: jfrog pipc --global=true --repo-resolve=repo-pypi

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: jfrog rt pip-install -r requirements.txt --no-cache-dir --force-reinstall

      - name: Install Build Tools
        run: pip install setuptools wheel

      - name: Package the project
        run: python setup.py sdist bdist_wheel

      - name: Publish
        run: jfrog rt upload "dist/*" repo-pypi/

      - name: Publish Build info With JFrog CLI
        run: |
          # Collect environment variables for the build
          jfrog rt build-collect-env
          # Collect VCS details from git and add them to the build
          jfrog rt build-add-git
          # Publish build info
          jfrog rt build-publish
